export { default as recommend } from './__recommend.md'
export { default as demo1 } from './__demo1.md'
export { default as api } from './__api.md'
export { default as base } from './base.vue'
export { default as code } from './code.md'